x-default-opts: &default-opts
  restart: "no"
  tty: true
  stdin_open: true
  privileged: true
  ipc: private

services:
  kalilinux:
    <<: *default-opts
    build:
      context: .
      dockerfile: dockerfile
    container_name: kalilinux
    network_mode: "host"
